name: Save Model Output to Text File

on:
    workflow_dispatch:
        inputs:
            model:
                description: "The model to run with Ollama (e.g., llama3.2)"
                required: true
                default: "llama3.2"
            prompt:
                description: "The prompt to query the model"
                required: true
                default: "Generate a Random Wisdom Quote in Korean with its Meaning in English"
            output_filename:
                description: "The output filename"
                required: true
                default: "model_answer.txt"
            silent:
                description: "Suppresses model output and loading animation"
                required: false
                type: "choice"
                options:
                    - true
                    - false
                default: "true"

permissions:
    contents: write # Allow workflow to push changes

jobs:
    save_output_to_file:
        runs-on: ubuntu-latest

        env:
            OUTPUT_FILE_PATH: ./generated-content/${{ github.event.inputs.output_filename }}

        steps:
            # Checkout nino-cli repository instead of the current one
            - name: Checkout nino-cli repository
              uses: actions/checkout@v4
              with:
                  repository: lucianoayres/nino-cli

            # Install Ollama
            - name: Install Ollama
              run: |
                  curl -fsSL https://ollama.com/install.sh | sh

            # Run Ollama server in the background
            - name: Run Ollama server in the background
              run: |
                  nohup ollama serve & # Start Ollama server in the background

            # Run the specified model using the 'model' input
            - name: Run llama model
              run: |
                  ollama run ${{ github.event.inputs.model }}

            # Set up Go environment
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.23"

            # Build nino-cli Go script from the cloned repository
            - name: Build Go script
              run: |
                  make build

            # Run nino-cli with the model, prompt, and silent arguments
            - name: Run Go script
              run: |
                  ./nino \
                    -model "${{ github.event.inputs.model }}" \
                    -prompt "${{ github.event.inputs.prompt }}" \
                    -output "${{ env.OUTPUT_FILE_PATH }}" \
                    ${{ github.event.inputs.silent == 'true' && '-silent' || '' }}

            # Display saved file content on the console
            - name: Display saved file content
              run: |
                  cat "${{ env.OUTPUT_FILE_PATH }}"

            # Commit generated file
            - name: Commit Changes
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add "${{ env.OUTPUT_FILE_PATH }}"
                  git commit -m "doc: add generated output file"
                  git push
